name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for your time to submit this issue, I will reply as soon as I see this issue"
        pr-message: "Thanks for your time and your work to submit this PR, I will merge it if it is applicable"
